const HEADER_CONTAINER = document.querySelector('header');
const HEADER_COLOR_BLACK = 'black';
const HEADER_COLOR_WHITE = 'white';
const HEADER_ITEM_ACTIVE_CLASS = 'menu__item_active';
const HEADER_ITEM_HOMEPAGE_ID = 'homepage';
const HEADER_ITEM_ARTICLES_ID = 'articles';

export { HEADER_CONTAINER, HEADER_COLOR_BLACK, HEADER_COLOR_WHITE, HEADER_ITEM_ACTIVE_CLASS, HEADER_ITEM_HOMEPAGE_ID, HEADER_ITEM_ARTICLES_ID };